<?php

namespace LocIHM\LocationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratRepository extends EntityRepository
{
	public function findIdVehUseInContrat($dateDebut, $dateFin)
	{
		
		$qb = $this->createQueryBuilder('contrat');
		$qb
			->where('contrat.dateDebut >= :dateDebut AND contrat.dateDebut <= :dateFin')
			->orWhere('contrat.dateFin >= :dateDebut AND contrat.dateFin <= :dateFin')
			->setParameter('dateDebut', $dateDebut)
			->setParameter('dateFin', $dateFin);
		
		$qb = $qb->getQuery()->getResult();

		return $qb;
	}
}
