<?php

namespace LocIHM\LocationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeRepository extends EntityRepository
{
	public function getVehNotInContrat($type, $requete)
	{
		$qb = $this->createQueryBuilder('vehicule');
		$qb
			->where('vehicule.typeVehicule = :type')
			->setParameter('type',$type)
			->where($qb->expr()->notIn('vehicule.id', $requete))
		;
		return $qb->getQuery()->getResult();
	}
}
