loc_ihm_location:
    resource: "@LocIHMLocationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    defaults: { _locale: fr }
    requirements:
        _locale: |fr|en

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}/
    requirements:
        _locale: fr|en

fos_user_profile:
    resource: "@LocIHMLocationBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/user/profile
    requirements:
        _locale: fr|en

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: fr|en

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
        _locale: fr|en

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/user/profile
    requirements:
        _locale: fr|en
