services:
    locihm_location.registration.form.type:
        class: LocIHM\LocationBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: locihm_location_registration }
    locihm_location.profile.form.type:
        class: LocIHM\LocationBundle\Form\Type\ProfileFormType
        tags:
            - {name: form.type, alias: locihm_location_user_registration }
    locihm_location.profile_edit:
        class: LocIHM\LocationBundle\EventListener\ProfileEditListener
        arguments: [@router]
        tags:
           - { name: kernel.event_subscriber }
    locihm_location.locale_listener:
        class: LocIHM\LocationBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }